package gui;

import core.Tarea;
import javax.swing.ImageIcon;

public class InfoTarea extends javax.swing.JFrame {

    static Tarea t;
    static String alt;

    /**
     * Creates new form InfoTarea
     */
    public InfoTarea(Tarea t, String alternativa) {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/iconogira.png")).getImage());
        this.setTitle("Información de la tarea " + t.getId());
        this.alt = alternativa;
        this.t = t;
        jTextFieldAsignada.setText(t.getAsignado());
        jTextFieldCreada.setText(t.getCreador());
        jTextFieldHorasEst.setText(String.valueOf(t.getHorasEstimadas()));
        jTextFieldHorasRea.setText(String.valueOf(t.getHorasReales()));
        jTextFieldId.setText(String.valueOf(t.getId()));
        jTextFieldResumen.setText(t.getResumen());
        jTextFieldTarea.setText(String.valueOf(t.getNumeroT()));
        jTextAreaAlternativa.setText(alt);
        this.setSize(465, 600);
        this.setLocationRelativeTo(null);
        jTextFieldAsignada.setEditable(false);
        jTextFieldCreada.setEditable(false);
        jTextFieldHorasEst.setEditable(false);
        jTextFieldHorasRea.setEditable(false);
        jTextFieldId.setEditable(false);
        jTextFieldResumen.setEditable(false);
        jTextFieldTarea.setEditable(false);
        jTextAreaAlternativa.setEditable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldId = new javax.swing.JTextField();
        jTextFieldTarea = new javax.swing.JTextField();
        jTextFieldResumen = new javax.swing.JTextField();
        jTextFieldHorasEst = new javax.swing.JTextField();
        jTextFieldHorasRea = new javax.swing.JTextField();
        jTextFieldCreada = new javax.swing.JTextField();
        jTextFieldAsignada = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaAlternativa = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 390));
        setPreferredSize(new java.awt.Dimension(400, 390));

        jLabel1.setText("Id Tarea");

        jLabel2.setText("Numero Tarea");

        jLabel3.setText("Resumen");

        jLabel4.setText("Horas estimadas");

        jLabel5.setText("Horas reales");

        jLabel6.setText("Creada por ");

        jLabel7.setText("Alternativa");

        jTextFieldId.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldId.setText("jTextField1");

        jTextFieldTarea.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldTarea.setText("jTextField2");

        jTextFieldResumen.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldResumen.setText("jTextField3");
        jTextFieldResumen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldResumenActionPerformed(evt);
            }
        });

        jTextFieldHorasEst.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldHorasEst.setText("jTextField4");

        jTextFieldHorasRea.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldHorasRea.setText("jTextField5");

        jTextFieldCreada.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldCreada.setText("jTextField6");

        jTextFieldAsignada.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldAsignada.setText("jTextField7");

        jTextAreaAlternativa.setColumns(20);
        jTextAreaAlternativa.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jTextAreaAlternativa.setLineWrap(true);
        jTextAreaAlternativa.setRows(5);
        jTextAreaAlternativa.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextAreaAlternativa);

        jLabel8.setText("Asignada a");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldId, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldTarea, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldResumen, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldHorasEst, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldHorasRea, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldCreada, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldAsignada)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldResumen, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldHorasEst, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldHorasRea, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCreada, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldAsignada, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                    .addComponent(jLabel7))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldResumenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldResumenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldResumenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InfoTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InfoTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InfoTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InfoTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InfoTarea(t, alt).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaAlternativa;
    private javax.swing.JTextField jTextFieldAsignada;
    private javax.swing.JTextField jTextFieldCreada;
    private javax.swing.JTextField jTextFieldHorasEst;
    private javax.swing.JTextField jTextFieldHorasRea;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldResumen;
    private javax.swing.JTextField jTextFieldTarea;
    // End of variables declaration//GEN-END:variables
}
