package gui;


import core.Administrador;
import core.BDConsulter;
import core.Tarea;
import gui.ConflictedTask;
import java.sql.Date;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;

public class Inicio extends javax.swing.JFrame {

    public ArrayList<Tarea> tareas = new ArrayList<>();
    public ArrayList<Tarea> tareasAnalisis = new ArrayList<>();
    static Date fechaDesde;
    public Date fechaHasta;
    Administrador admin;
    public static String DATABASE_URL;
    public static String DATABASE_USER;
    public static String DATABASE_PASS;

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/iconogira.png")).getImage());
        this.setLocationRelativeTo(null);
        this.setTitle("GIIA");
        
        DefaultListModel<String> model = new DefaultListModel<>();
        jListIntegrantes.setModel(model);
        jTextFieldMediaTiempoEst.setEditable(false);
        jTextFieldMediaTiempoReal.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBoxGrupos = new javax.swing.JComboBox<>();
        jComboBoxProyecto = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        desdeTF = new javax.swing.JTextField();
        hastaTF = new javax.swing.JTextField();
        aprenderBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListIntegrantes = new javax.swing.JList<>();
        jLabel11 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelEstadisticas = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabelMediaReal = new javax.swing.JLabel();
        jLabelMediaEstimada = new javax.swing.JLabel();
        jTextFieldMediaTiempoEst = new javax.swing.JTextField();
        jTextFieldMediaTiempoReal = new javax.swing.JTextField();

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo2.png"))); // NOI18N
        jLabel10.setText("jLabel10");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        setMaximumSize(new java.awt.Dimension(720, 700));
        setMinimumSize(new java.awt.Dimension(639, 336));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Grupo:");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Proyecto:");

        jComboBoxGrupos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxGruposItemStateChanged(evt);
            }
        });

        jComboBoxProyecto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxProyectoItemStateChanged(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/infochik2.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Desde:");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Hasta:");

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Analizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        desdeTF.setText("2018-02-02");
        desdeTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desdeTFActionPerformed(evt);
            }
        });

        hastaTF.setText("2018-05-28");
        hastaTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hastaTFActionPerformed(evt);
            }
        });

        aprenderBtn.setText("Aprender");
        aprenderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aprenderBtnActionPerformed(evt);
            }
        });

        jListIntegrantes.setBackground(new java.awt.Color(254, 254, 254));
        jScrollPane1.setViewportView(jListIntegrantes);

        jLabel11.setText("Integrantes:");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabelEstadisticas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelEstadisticas.setText("Estadísticas");

        jLabelMediaReal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelMediaReal.setText("Media Tiempo Real:");

        jLabelMediaEstimada.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelMediaEstimada.setText("Media Tiempo Estimado:");
        jLabelMediaEstimada.setMaximumSize(new java.awt.Dimension(37, 16));

        jTextFieldMediaTiempoEst.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextFieldMediaTiempoReal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE))
                            .addGap(12, 12, 12)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jComboBoxProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jComboBoxGrupos, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(desdeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(13, 13, 13)
                                    .addComponent(hastaTF, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addComponent(jSeparator2)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabelEstadisticas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(109, 109, 109))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabelMediaEstimada, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                                .addComponent(jLabelMediaReal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldMediaTiempoEst)
                                .addComponent(jTextFieldMediaTiempoReal))))
                    .addComponent(aprenderBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxGrupos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(desdeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hastaTF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelEstadisticas, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelMediaEstimada, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldMediaTiempoEst, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelMediaReal)
                            .addComponent(jTextFieldMediaTiempoReal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(aprenderBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void desdeTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desdeTFActionPerformed

    }//GEN-LAST:event_desdeTFActionPerformed

    private void hastaTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hastaTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hastaTFActionPerformed

    private void aprenderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aprenderBtnActionPerformed

        boolean mal = false;
        if (desdeTF.getText().equals("yyyy-mm-dd")) {//CONTROLA QUE HAYA PUESTO FECHAS 
            MessageHasta nuevo = new MessageHasta();
            mal = true;
            nuevo.setVisible(true);
        } else {
            fechaDesde = Date.valueOf(desdeTF.getText());
        }
        if (hastaTF.getText().equals("yyyy-mm-dd")) {//CONTROLA QUE HAYA PUESTO FECHAS 
            MessageDesde nuevo = new MessageDesde();
            nuevo.setVisible(true);
            mal = true;
        } else {
            fechaHasta = Date.valueOf(hastaTF.getText());//FECHA FIN APRENDIZAJE
        }

        if (!mal) {
            tareas = this.getTareas(fechaDesde, fechaHasta);//TENDRIA QUE GUARDAR EN TAREAS LAS TAREAS DENTRO DEL RANGO
            tareasAnalisis = this.getTareas(fechaHasta, new java.sql.Date(Calendar.getInstance().getTime().getTime()));
            admin = new Administrador(tareas, tareasAnalisis);
        }
        AprendioMsj nuevos = new AprendioMsj();
        nuevos.setVisible(true);

        /*List<String> integrantes = jList1.getSelectedValuesList();
        for (String s : integrantes) {
            System.out.println("Integrante seleccionado: " + s);
        }*/
        
        jTextFieldMediaTiempoEst.setText(String.valueOf(admin.getMediaTiempoEstimado()));
        jTextFieldMediaTiempoReal.setText(String.valueOf(admin.getMediaTiempoReal()));
    }//GEN-LAST:event_aprenderBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //admin = new Administrador(new ArrayList<Tarea> (), new ArrayList<Tarea> ());//solo para test
        ConflictedTask nuevo = new ConflictedTask();
        nuevo.setInicio(this);
        nuevo.cargarTareas();
        nuevo.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Informacion info = new Informacion();
        info.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBoxGruposItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxGruposItemStateChanged
        // TODO add your handling code here:
        setProyectos();
        loadIntegrantes();
    }//GEN-LAST:event_jComboBoxGruposItemStateChanged

    private void jComboBoxProyectoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxProyectoItemStateChanged
        // TODO add your handling code here:
        loadIntegrantes();
    }//GEN-LAST:event_jComboBoxProyectoItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aprenderBtn;
    private javax.swing.JTextField desdeTF;
    private javax.swing.JTextField hastaTF;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBoxGrupos;
    private javax.swing.JComboBox<String> jComboBoxProyecto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelEstadisticas;
    private javax.swing.JLabel jLabelMediaEstimada;
    private javax.swing.JLabel jLabelMediaReal;
    private javax.swing.JList<String> jListIntegrantes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextFieldMediaTiempoEst;
    private javax.swing.JTextField jTextFieldMediaTiempoReal;
    // End of variables declaration//GEN-END:variables

    private ArrayList<Tarea> getTareas(Date desde, Date hasta) {
        BDConsulter consulter = new BDConsulter(DATABASE_URL, DATABASE_USER, DATABASE_PASS);//genero la clase, que se conecta a la base postgresql
        consulter.connect();//establezco la conexion

        //Si no hay ningun integrante seleccionado, selecciono todos
        List<String> integrantesSeleccionados = jListIntegrantes.getSelectedValuesList();
        DefaultListModel<String> model = (DefaultListModel<String>) jListIntegrantes.getModel();
        List<String> integrantes = new ArrayList<String>();
        if (integrantesSeleccionados.size() == 0) {
            for (int i = 0; i < model.getSize(); i++) {
                System.out.println((model.getElementAt(i)));
                integrantes.add(model.getElementAt(i));
            }
            integrantesSeleccionados = integrantes;
        }

        ArrayList<Tarea> tareas = new ArrayList<>();
        for (String s : integrantesSeleccionados) {
            tareas.addAll(consulter.getTareas(desde, hasta, (String) jComboBoxProyecto.getSelectedItem(), (String) jComboBoxGrupos.getSelectedItem(), s));//obtengo las tareas creadas entre un rango de fecha dado
        }
        consulter.disconnect();//termino la conexion con la base//termino la conexion con la base
        return tareas;
    }

    private float getPromedio(ArrayList<Tarea> tareas) {
        int horasReales = 0;
        int horasEstimadas = 0;
        for (Tarea t : tareas) {
            horasReales += t.getHorasReales();
            horasEstimadas += t.getHorasEstimadas();
        }
        return (1 - (horasReales / horasEstimadas));
    }

    public Administrador getAdministrador() {
        return admin;
    }

    private void setGrupos() {
        BDConsulter consulter = new BDConsulter(DATABASE_URL, DATABASE_USER, DATABASE_PASS);//genero la clase, que se conecta a la base postgresql
        consulter.connect();//establezco la conexion
        ArrayList<String> grupos = consulter.getGrupos();
        consulter.disconnect();//termino la conexion con la base//termino la conexion con la base
        for (String s : grupos) {
            jComboBoxGrupos.addItem(s);
        }
    }

    private void setProyectos() {
        BDConsulter consulter = new BDConsulter(DATABASE_URL, DATABASE_USER, DATABASE_PASS);//genero la clase, que se conecta a la base postgresql
        consulter.connect();//establezco la conexion
        ArrayList<String> proyectos = consulter.getProyectos((String) jComboBoxGrupos.getSelectedItem());
        consulter.disconnect();//termino la conexion con la base//termino la conexion con la base
        jComboBoxProyecto.removeAllItems();
        for (String s : proyectos) {
            jComboBoxProyecto.addItem(s);
        }
    }

    private void loadIntegrantes() {
        System.out.println("Loading integrantes");
        BDConsulter consulter = new BDConsulter(DATABASE_URL, DATABASE_USER, DATABASE_PASS);//genero la clase, que se conecta a la base postgresql
        consulter.connect();//establezco la conexion
        ArrayList<String> integrantes = consulter.getIntegrantes((String) jComboBoxGrupos.getSelectedItem(), (String) jComboBoxProyecto.getSelectedItem());
        consulter.disconnect();//termino la conexion con la base//termino la conexion con la base
        //jListIntegrantes.removeAll(); 
        ((DefaultListModel)jListIntegrantes.getModel()).clear();
        System.out.println("REMOVING integ");
        for (String s : integrantes) {
            ((DefaultListModel)jListIntegrantes.getModel()).addElement(s);
        }
    }

    void setDatabaseData(String url, String user, String pass) {
        DATABASE_URL = url;
        DATABASE_USER = user;
        DATABASE_PASS = pass;
    }

    void preloadInterface() {
        setGrupos();
        setProyectos();
        loadIntegrantes();
        //jComboBoxGrupos.setSelectedItem("Empáticos");
        //loadIntegrantes();
    }

}
